### ISSUE TITLE
Hello This is a Issue :D 

### ISSUE THREAD

**Issue by HarshPatel5940** [srm-kzilla/git-it#1]
we may use this like suggestions and whatnot....

**Comment by alou-S** [comment]
The issue doesn't seem to be well described here. Would suggest vhhih

**Comment by alou-S** [comment]
Your issue doesn't seem to be described properly. Would suggest you to be more clear so the devs may understand. /s

**Comment by HarshPatel5940** [comment]
This was an issue i made for fun during the session, let me go ahead and close it to avoid confusion.
